id: I8FBA244D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T02:39:13+00:00'
last_modified: '2022-06-08T10:26:54.627363+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1886
  title: ཀརྨ་པ་ཆོས་དབྱིངས་རྡོ་རྗེའི་རྣམ་ཐར་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4F24:
      image_group_id: I1CZ1969
      title: ''
      total_pages: 94
      order: 1
      base_file: 4F24.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
